//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Security.Cryptography.X509Certificates;

namespace PrefeituraSPNotaSincrono
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", ConfigurationName="PrefeituraSPNotaSincrono.LoteNFeSoap")]
    public interface LoteNFeSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.EnvioRPSResponse> EnvioRPSAsync(PrefeituraSPNotaSincrono.EnvioRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.EnvioLoteRPSResponse> EnvioLoteRPSAsync(PrefeituraSPNotaSincrono.EnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(PrefeituraSPNotaSincrono.TesteEnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.CancelamentoNFeResponse> CancelamentoNFeAsync(PrefeituraSPNotaSincrono.CancelamentoNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaNFeResponse> ConsultaNFeAsync(PrefeituraSPNotaSincrono.ConsultaNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(PrefeituraSPNotaSincrono.ConsultaNFeRecebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(PrefeituraSPNotaSincrono.ConsultaNFeEmitidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaLoteResponse> ConsultaLoteAsync(PrefeituraSPNotaSincrono.ConsultaLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(PrefeituraSPNotaSincrono.ConsultaInformacoesLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaCNPJResponse> ConsultaCNPJAsync(PrefeituraSPNotaSincrono.ConsultaCNPJRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioRPSRequest()
        {
        }
        
        public EnvioRPSRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioRPSResponse()
        {
        }
        
        public EnvioRPSResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioLoteRPSRequest()
        {
        }
        
        public EnvioLoteRPSRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioLoteRPSResponse()
        {
        }
        
        public EnvioLoteRPSResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public TesteEnvioLoteRPSRequest()
        {
        }
        
        public TesteEnvioLoteRPSRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public TesteEnvioLoteRPSResponse()
        {
        }
        
        public TesteEnvioLoteRPSResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public CancelamentoNFeRequest()
        {
        }
        
        public CancelamentoNFeRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public CancelamentoNFeResponse()
        {
        }
        
        public CancelamentoNFeResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRequest()
        {
        }
        
        public ConsultaNFeRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeResponse()
        {
        }
        
        public ConsultaNFeResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRecebidasRequest()
        {
        }
        
        public ConsultaNFeRecebidasRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeRecebidasResponse()
        {
        }
        
        public ConsultaNFeRecebidasResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeEmitidasRequest()
        {
        }
        
        public ConsultaNFeEmitidasRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeEmitidasResponse()
        {
        }
        
        public ConsultaNFeEmitidasResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaLoteRequest()
        {
        }
        
        public ConsultaLoteRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaLoteResponse()
        {
        }
        
        public ConsultaLoteResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaInformacoesLoteRequest()
        {
        }
        
        public ConsultaInformacoesLoteRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaInformacoesLoteResponse()
        {
        }
        
        public ConsultaInformacoesLoteResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaCNPJRequest()
        {
        }
        
        public ConsultaCNPJRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaCNPJResponse()
        {
        }
        
        public ConsultaCNPJResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface LoteNFeSoapChannel : PrefeituraSPNotaSincrono.LoteNFeSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class LoteNFeSoapClient : System.ServiceModel.ClientBase<PrefeituraSPNotaSincrono.LoteNFeSoap>, PrefeituraSPNotaSincrono.LoteNFeSoap
    {
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials, X509Certificate2 certificate);

        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration, X509Certificate2 certificate) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), LoteNFeSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials, certificate);
        }
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress, X509Certificate2 certificate) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials, certificate);
        }
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress, X509Certificate2 certificate) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials, certificate);
        }
        
        public LoteNFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.EnvioRPSResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.EnvioRPSAsync(PrefeituraSPNotaSincrono.EnvioRPSRequest request)
        {
            return base.Channel.EnvioRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.EnvioRPSResponse> EnvioRPSAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.EnvioRPSRequest inValue = new PrefeituraSPNotaSincrono.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).EnvioRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.EnvioLoteRPSResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.EnvioLoteRPSAsync(PrefeituraSPNotaSincrono.EnvioLoteRPSRequest request)
        {
            return base.Channel.EnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.EnvioLoteRPSResponse> EnvioLoteRPSAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.EnvioLoteRPSRequest inValue = new PrefeituraSPNotaSincrono.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).EnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.TesteEnvioLoteRPSResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.TesteEnvioLoteRPSAsync(PrefeituraSPNotaSincrono.TesteEnvioLoteRPSRequest request)
        {
            return base.Channel.TesteEnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.TesteEnvioLoteRPSRequest inValue = new PrefeituraSPNotaSincrono.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).TesteEnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.CancelamentoNFeResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.CancelamentoNFeAsync(PrefeituraSPNotaSincrono.CancelamentoNFeRequest request)
        {
            return base.Channel.CancelamentoNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.CancelamentoNFeResponse> CancelamentoNFeAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.CancelamentoNFeRequest inValue = new PrefeituraSPNotaSincrono.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).CancelamentoNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaNFeResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.ConsultaNFeAsync(PrefeituraSPNotaSincrono.ConsultaNFeRequest request)
        {
            return base.Channel.ConsultaNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaNFeResponse> ConsultaNFeAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.ConsultaNFeRequest inValue = new PrefeituraSPNotaSincrono.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).ConsultaNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaNFeRecebidasResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.ConsultaNFeRecebidasAsync(PrefeituraSPNotaSincrono.ConsultaNFeRecebidasRequest request)
        {
            return base.Channel.ConsultaNFeRecebidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.ConsultaNFeRecebidasRequest inValue = new PrefeituraSPNotaSincrono.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).ConsultaNFeRecebidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaNFeEmitidasResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.ConsultaNFeEmitidasAsync(PrefeituraSPNotaSincrono.ConsultaNFeEmitidasRequest request)
        {
            return base.Channel.ConsultaNFeEmitidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.ConsultaNFeEmitidasRequest inValue = new PrefeituraSPNotaSincrono.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).ConsultaNFeEmitidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaLoteResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.ConsultaLoteAsync(PrefeituraSPNotaSincrono.ConsultaLoteRequest request)
        {
            return base.Channel.ConsultaLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaLoteResponse> ConsultaLoteAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.ConsultaLoteRequest inValue = new PrefeituraSPNotaSincrono.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).ConsultaLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaInformacoesLoteResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.ConsultaInformacoesLoteAsync(PrefeituraSPNotaSincrono.ConsultaInformacoesLoteRequest request)
        {
            return base.Channel.ConsultaInformacoesLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.ConsultaInformacoesLoteRequest inValue = new PrefeituraSPNotaSincrono.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).ConsultaInformacoesLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaCNPJResponse> PrefeituraSPNotaSincrono.LoteNFeSoap.ConsultaCNPJAsync(PrefeituraSPNotaSincrono.ConsultaCNPJRequest request)
        {
            return base.Channel.ConsultaCNPJAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrefeituraSPNotaSincrono.ConsultaCNPJResponse> ConsultaCNPJAsync(int VersaoSchema, string MensagemXML)
        {
            PrefeituraSPNotaSincrono.ConsultaCNPJRequest inValue = new PrefeituraSPNotaSincrono.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((PrefeituraSPNotaSincrono.LoteNFeSoap)(this)).ConsultaCNPJAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;

                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://nfe.prefeitura.sp.gov.br/ws/lotenfe.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://nfe.prefeitura.sp.gov.br/ws/lotenfe.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LoteNFeSoap,
            
            LoteNFeSoap12,
        }
    }
}
